apiVersion: apps/v1
kind: Deployment
metadata:
  name: buzzloop-spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buzzloop-spring-backend
  template:
    metadata:
      labels:
        app: buzzloop-spring-backend
    spec:
      containers:
        - name: buzzloop-spring-backend
          image: redouansammour/buzzloop-spring-backend:latest
          ports:
            - containerPort: 8080
