name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check for JAR file
        run: |
          if [ ! -f "build/libs/*.jar" ]; then
            echo "Error: JAR file not found in build/libs folder."
            exit 1
          fi
          
      - name: Build with Gradle
        run: |
          ls -l  # Just to make sure we're in the correct directory
          gradle build --no-daemon  # Use the 'gradle' command directly

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: redouansammour/buzzloop-spring-backend
          tags: latest
