name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          ls -l  # Just to make sure we're in the correct directory
          ./gradlew build --no-daemon

      - name: Check contents of build/libs folder
        run: |
          ls -l build/libs

      - name: Copy JAR files to Docker context
        run: cp build/libs/*.jar $GITHUB_WORKSPACE
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t redouansammour/buzzloop-spring-backend .
          docker push redouansammour/buzzloop-spring-backend:latest
