name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Change to project directory
        run: cd buzzloop-backend  # Change to the directory where your Gradle project is located

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: redouansammour/buzzloop-spring-backend
          tags: latest
